/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;

/**
 *
 * @author User
 */
public class FrmSinaisProntosInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmSinaisProntosInternal
     */
    public FrmSinaisProntosInternal() {
        initComponents();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboSinais = new javax.swing.JComboBox();
        lblLibra2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Palavras ténicas no curso de TI");

        cboSinais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Algoritmo", "Banco de Dados", "C#", "Else if", "Fluxograma", "IDE", "If", "Interface", "Layout", "Metodo", "Next", "Programação", "User", " " }));
        cboSinais.setToolTipText("");
        cboSinais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSinaisActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecione:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSinais, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLibra2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSinais, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLibra2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboSinaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSinaisActionPerformed
        if (cboSinais.getSelectedIndex() == 0){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Algoritmo.gif")));
        }
        if (cboSinais.getSelectedIndex() == 1){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Banco_Dados.gif")));
        }
        if (cboSinais.getSelectedIndex() == 2){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/C#.gif")));
        }
        if (cboSinais.getSelectedIndex() == 3){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Else_if.gif")));
        }
        if (cboSinais.getSelectedIndex() == 4){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Fluxograma.gif")));
        }
        if (cboSinais.getSelectedIndex() == 5){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/IDE.gif")));
        }
        if (cboSinais.getSelectedIndex() == 6){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/IF.gif")));
        }
        if (cboSinais.getSelectedIndex() == 7){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Interface.gif")));
        }
        if (cboSinais.getSelectedIndex() == 8){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Layout.gif")));
        }
        if (cboSinais.getSelectedIndex() == 9){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Metodo.gif")));
        }
        if (cboSinais.getSelectedIndex() == 10){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Next.gif")));
        }
        if (cboSinais.getSelectedIndex() == 10){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Programacao.gif")));
        }
        if (cboSinais.getSelectedIndex() == 11){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/User.gif")));
        }
    }//GEN-LAST:event_cboSinaisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboSinais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLibra2;
    // End of variables declaration//GEN-END:variables
}
