/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Aluno
 */
public class FrnSinaisProntos extends javax.swing.JFrame {

    /**
     * Creates new form FrnSinaisProntos
     */
    public FrnSinaisProntos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboSinais = new javax.swing.JComboBox();
        lblLibra2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Palavras ténicas no curso de TI");

        cboSinais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Algoritmo", "Banco de Dados", "C#", "Else if", "Fluxograma", "IDE", "If", "Interface", "Layout", "Metodo", "Next", "Programação", "User", " " }));
        cboSinais.setToolTipText("");
        cboSinais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSinaisActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecione:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSinais, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblLibra2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSinais, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(lblLibra2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboSinaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSinaisActionPerformed
        if (cboSinais.getSelectedIndex() == 0){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Algoritmo.gif")));
        }
        if (cboSinais.getSelectedIndex() == 1){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Banco_Dados.gif")));
        }
        if (cboSinais.getSelectedIndex() == 2){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/C#.gif")));
        }
        if (cboSinais.getSelectedIndex() == 3){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Else_if.gif")));
        }
        if (cboSinais.getSelectedIndex() == 4){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Fluxograma.gif")));
        }
        if (cboSinais.getSelectedIndex() == 5){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/IDE.gif")));
        }
        if (cboSinais.getSelectedIndex() == 6){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/IF.gif")));
        }
        if (cboSinais.getSelectedIndex() == 7){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Interface.gif")));
        }
        if (cboSinais.getSelectedIndex() == 8){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Layout.gif")));
        }
        if (cboSinais.getSelectedIndex() == 9){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Metodo.gif")));
        }
        if (cboSinais.getSelectedIndex() == 10){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Next.gif")));
        }
        if (cboSinais.getSelectedIndex() == 10){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/Programacao.gif")));
        }
        if (cboSinais.getSelectedIndex() == 11){
            lblLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/GIF/User.gif")));
        }
    }//GEN-LAST:event_cboSinaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrnSinaisProntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrnSinaisProntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrnSinaisProntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrnSinaisProntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrnSinaisProntos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboSinais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLibra2;
    // End of variables declaration//GEN-END:variables
}
